apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-eteczlcatracasfrontend
  name: pod-eteczlcatracasfrontend
spec:
  containers:
  - image: registry.gitlab.com/wagnermarques/eteczlcatracasfrontend/nginx-eteczlcatracasfrontend:v1
    name: pod-eteczlcatracasfrontend
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  imagePullSecrets:
    - name: secret-eteczlfrontend
