apiVersion: v1
kind: Service
metadata:
  name: svc-loadbalancer-eteczlcatracasfrontend
spec:
  type: LoadBalancer
  selector:
    run: pod-eteczlcatracasfrontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

