apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: svc-nodeport-eteczlcatracasfrontend
  name: svc-nodeport-eteczlcatracasfrontend
spec:
  ports:
  - name: svc-nodeport-eteczlcatracasfrontend
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: pod-eteczlcatracasfrontend
  type: NodePort
status:
  loadBalancer: {}

